<a href="https://colab.research.google.com/github/Rijann12/M_from_scrath/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## introduction to numpy
-  what wll we cover?
- creating arrays
- multidimensional array
- element wise operations
- comparison operations
- logical operations



### single dimensional array

In [2]:
import numpy as np

#### creating arrays

In [5]:
var = np.zeros(5)
print(type(var))


<class 'numpy.ndarray'>


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [13]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [17]:
a=np.array([1, 2, 3, 4])


In [18]:
a[2]=4

In [19]:
print(a)

[1 2 4 4]


In [20]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

#### create array with evenly spaced numbers within a specific range


In [22]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### multidimensional array

In [23]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
# create an MD Array of size (5,2)
# Generate a random array of size (3,5) with elements of yours choice
# update elements of an array with index

np.ones((5,2))
np.array(([1,2,3,4, 5,], [1, 2, 1, 1, 1], [1, 1, 1, 1, 1]))
a=np.array(([1,2,3,4, 5,], [1, 2, 1, 1, 1], [1, 1, 1, 1, 1]))
a
a[2]=([4, 4, 4, 4, 4])
print(a)
a[1, 3]= 100
a

[[1 2 3 4 5]
 [1 2 1 1 1]
 [4 4 4 4 4]]


array([[  1,   2,   3,   4,   5],
       [  1,   2,   1, 100,   1],
       [  4,   4,   4,   4,   4]])

In [40]:
#row change gareko
a[2]=[1, 1, 1, 1, 1]
a

array([[  1,   2,   3,   4,   5],
       [  1,   2,   1, 100,   1],
       [  1,   1,   1,   1,   1]])

In [42]:
#column change gareko (":":column ani kun column change garne tei halne jastai 2)
a[:, 2] = [3, 3, 3]
a

array([[  1,   2,   3,   4,   5],
       [  1,   2,   3, 100,   1],
       [  1,   1,   3,   1,   1]])