<a href="https://colab.research.google.com/github/Rijann12/ML_From_Scrath/blob/main/01%20Introduction_to_Ml/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy
 # what will we cover?
- creating arrays
- multidimensional array
- element wise operations
 -  comparison operations
 -  logical operations



### ✅Single dimensional array

In [2]:
import numpy as np

Creating arrays

In [5]:
var = np.zeros(5)
print(type(var))


<class 'numpy.ndarray'>


In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [13]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [17]:
a=np.array([1, 2, 3, 4])


In [18]:
a[2]=4

In [19]:
print(a)

[1 2 4 4]


In [20]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

 Create array with evenly spaced numbers within a specific range


In [22]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### ✅Multidimensional array

In [23]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
# create an MD Array of size (5,2)
# Generate a random array of size (3,5) with elements of yours choice
# update elements of an array with index

np.ones((5,2))
np.array(([1,2,3,4, 5,], [1, 2, 1, 1, 1], [1, 1, 1, 1, 1]))
a=np.array(([1,2,3,4, 5,], [1, 2, 1, 1, 1], [1, 1, 1, 1, 1]))
a
a[2]=([4, 4, 4, 4, 4])
print(a)
a[1, 3]= 100
a

[[1 2 3 4 5]
 [1 2 1 1 1]
 [4 4 4 4 4]]


array([[  1,   2,   3,   4,   5],
       [  1,   2,   1, 100,   1],
       [  4,   4,   4,   4,   4]])

In [40]:
#row change gareko
a[2]=[1, 1, 1, 1, 1]
a

array([[  1,   2,   3,   4,   5],
       [  1,   2,   1, 100,   1],
       [  1,   1,   1,   1,   1]])

In [42]:
#column change gareko (":":column ani kun column change garne tei halne jastai 2)
a[:, 2] = [3, 3, 3]
a

array([[  1,   2,   3,   4,   5],
       [  1,   2,   3, 100,   1],
       [  1,   1,   3,   1,   1]])

### Randomly Generated Arrays

- Numpy can create arrays filled with random numbers.
- To ensure the reproducibility, you can set a seed using np.random.seed()
- Everytime you run the code with np.random.seed(2), it will generate the exact
  same random numbers.
  If you can remove or chnage the seed values, the sequence of thr random numbers will be changed

In [59]:
# rand le chai random number 0 ra 1 ko bich ko matra dinxa
np.random.rand(3)

array([0.59377923, 0.21840037, 0.66374897])

In [82]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [89]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [95]:
np.random.randn(5, 2)

array([[ 0.65661947,  0.12480683],
       [-0.43570392,  0.97217931],
       [-0.24071114, -0.82412345],
       [ 0.56813272,  0.01275832],
       [ 1.18906073, -0.07359332]])

In [96]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5,2))


array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### Element wise operations


In [97]:
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [99]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [100]:
# Comparison operations
# You can perform element-wise comparison and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [101]:
a >= 2

array([False, False,  True,  True,  True])

In [102]:
a > b

array([False, False, False, False, False])

In [103]:
# Summarizing
# NumPy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [104]:
# Standard Deviation
a.std()

1.4142135623730951

In [105]:
# minimum value of an array
a.min()

0

In [106]:
# max value of an array
a.max()

4

In [107]:
# sum of the elements of an array
a.sum()

10